// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lab2.WebAPI.Models
{
    public partial class GetAllCoursesResult
    {
        public int Crs_Id { get; set; }
        [StringLength(50)]
        public string Crs_Name { get; set; }
        public int? Crs_Duration { get; set; }
        [StringLength(50)]
        public string Top_Name { get; set; }
    }
}
