// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Lab2.WebAPI.Models
{
    public partial class GetStudentGradesByIdResult
    {
        public int St_Id { get; set; }
        [StringLength(50)]
        public string St_Fname { get; set; }
        public string St_Lname { get; set; }
        public int? St_Age { get; set; }
        public int Crs_Id { get; set; }
        [StringLength(50)]
        public string Crs_Name { get; set; }
        public int? Grade { get; set; }
    }
}
