// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Lab2.WebAPI.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Lab2.WebAPI.Models
{
    public partial interface IITIContextProcedures
    {
        Task<List<GetAllCoursesResult>> GetAllCoursesAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentGradesByIdResult>> GetStudentGradesByIdAsync(int? studentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetStudentsByAgeRangeResult>> GetStudentsByAgeRangeAsync(int? age1, int? age2, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
